python pctm_v00.py \
--year 2018 \
--month 4 \
--day 1 \
--last_day 3 \
--interval_minutes 30 \
--device "cpu" \
--if_mixing_str "False" \
--sim_dimension 2 \
--layer_type "layer_1" \
--if_plot_result_str "True" \
--plot_interval 24 \
--data_folder '/Users/yaoyichen/dataset/auto_experiment/experiment_0/' \
--sub_data_folder '201804' \
--result_folder '/Users/yaoyichen/Desktop/auto_experiment/experiment_0/real_assimilation_satellite_20180401/' \
--geoschem_co2_file "GEOSChem.SpeciesConc.20190701_0000z.nc4" \
--flux_type "carbon_tracker" \
--flux_file_name "monthly_flux_np/CT2019B.flux1x1.201804_reshape.npy" \
--problem_type "assimilation" \
--experiment_type "real" \
--obs_type "satellite" \
--cinit_type_assimilation "constant_obs" \
--iteration_number 50 \
--early_stop_value 0.2e-6 \
--lr_cinit 2e-5 \
--if_background "True" \
--background_weight 0.5

